import { memberListType, } from "./members-list-type";

const MockInitialTeamMembers: memberListType = [
    { name: 'Islam' },
    { name: 'Jean-Christophe' },
    { name: 'Kevin' },
    { name: 'Vincent' },
    { name: 'Cherif' },
    { name: 'Oum' },
    { name: 'Jeremy' },
    { name: 'Jean' },

    // Derniers membres à être passés
    //{ name: 'Claudia' },

    // Absent pour cette semaine
    //{ name: 'Virgil' },

    // Immunité temporaire
    //{ name: 'Soumaya'},

    // Plus dans l'équipe
    //{ name: 'Swan' },
    //{ name: 'Hakima' },
    //{ name: 'Aya' },
    //{ name: 'Stéphane' },
    //{ name: 'Wendy' },
];

const MockCurrentTeamMembers: memberListType = [
    { name: 'Islam' },
    { name: 'Jean-Christophe' },
    { name: 'Kevin' },
    { name: 'Vincent' },
    { name: 'Cherif' },
    { name: 'Oum' },
    { name: 'Jeremy' },
    { name: 'Jean' },

    // Derniers membres à être passés
    //{ name: 'Claudia' },

    // Absent pour cette semaine
    //{ name: 'Virgil' },

    // Immunité temporaire
    //{ name: 'Soumaya'},

    // Plus dans l'équipe
    //{ name: 'Swan' },
    //{ name: 'Hakima' },
    //{ name: 'Aya' },
    //{ name: 'Stéphane' },
    //{ name: 'Wendy' },
];

const MockBeginingTimer: number = 9 * 60;
const MockEndingTimer: number = 10 * 60;
const MockCurrentDate: Date = new Date;

export { MockInitialTeamMembers, MockCurrentTeamMembers, MockBeginingTimer, MockEndingTimer, MockCurrentDate }

const LongMockInitialTeamMembers: memberListType = [
    { name: 'Vincent' },
    { name: 'Kevin' },
    { name: 'Jean' },
    { name: 'Jean-Christophe' },
    { name: 'Hakima' },
    { name: 'Aya' },
    { name: 'Virgil' },
    { name: 'Wendy' },
    { name: 'Oum' },
    { name: 'Jeremy' },
    { name: 'Claudia' },
    { name: 'Vincent 1' },
    { name: 'Kevin 1' },
    { name: 'Jean 1' },
    { name: 'Jean-Christophe 1' },
    { name: 'Hakima 1' },
    { name: 'Aya 1' },
    { name: 'Virgil 1' },
    { name: 'Stéphane 1' },
    { name: 'Wendy 1' },
    { name: 'Oum 1' },
    { name: 'Jeremy 1' },
    { name: 'Claudia 1' },
    { name: 'Vincent 2' },
    { name: 'Kevin 2' },
    { name: 'Jean 2' },
    { name: 'Jean-Christophe 2' },
    { name: 'Hakima 2' },
    { name: 'Aya 2' },
    { name: 'Virgil 2' },
    { name: 'Stéphane 2' },
    { name: 'Wendy 2' },
    { name: 'Oum 2' },
    { name: 'Jeremy 2' },
    { name: 'Claudia 2' },
    { name: 'Vincent 3' },
    { name: 'Kevin 3' },
    { name: 'Jean 3' },
    { name: 'Jean-Christophe 3' },
    { name: 'Hakima 3' },
    { name: 'Aya 3' },
    { name: 'Virgil 3' },
    { name: 'Stéphane 3' },
    { name: 'Wendy 3' },
    { name: 'Oum 3' },
    { name: 'Jeremy 3' },
    { name: 'Claudia 3' },
    { name: 'Vincent 4' },
    { name: 'Kevin 4' },
    { name: 'Jean 4' },
    { name: 'Jean-Christophe 4' },
    { name: 'Hakima 4' },
    { name: 'Aya 4' },
    { name: 'Virgil 4' },
    { name: 'Stéphane 4' },
    { name: 'Wendy 4' },
    { name: 'Oum 4' },
    { name: 'Jeremy 4' },
    { name: 'Claudia 4' },
    { name: 'Vincent 5' },
    { name: 'Kevin 5' },
    { name: 'Jean 5' },
    { name: 'Jean-Christophe 5' },
    { name: 'Hakima 5' },
    { name: 'Aya 5' },
    { name: 'Virgil 5' },
    { name: 'Stéphane 5' },
    { name: 'Wendy 5' },
    { name: 'Oum 5' },
    { name: 'Jeremy 5' },
    { name: 'Claudia 5' },
];

const LongMockCurrentTeamMembers: memberListType = [
    { name: 'Vincent' },
    { name: 'Kevin' },
    { name: 'Jean' },
    { name: 'Jean-Christophe' },
    { name: 'Hakima' },
    { name: 'Aya' },
    { name: 'Virgil' },
    { name: 'Stéphane' },
    { name: 'Wendy' },
    { name: 'Oum' },
    { name: 'Jeremy' },
    { name: 'Claudia' },
    { name: 'Vincent 1' },
    { name: 'Kevin 1' },
    { name: 'Jean 1' },
    { name: 'Jean-Christophe 1' },
    { name: 'Hakima 1' },
    { name: 'Aya 1' },
    { name: 'Virgil 1' },
    { name: 'Stéphane 1' },
    { name: 'Wendy 1' },
    { name: 'Oum 1' },
    { name: 'Jeremy 1' },
    { name: 'Claudia 1' },
    { name: 'Vincent 2' },
    { name: 'Kevin 2' },
    { name: 'Jean 2' },
    { name: 'Jean-Christophe 2' },
    { name: 'Hakima 2' },
    { name: 'Aya 2' },
    { name: 'Virgil 2' },
    { name: 'Stéphane 2' },
    { name: 'Wendy 2' },
    { name: 'Oum 2' },
    { name: 'Jeremy 2' },
    { name: 'Claudia 2' },
    { name: 'Vincent 3' },
    { name: 'Kevin 3' },
    { name: 'Jean 3' },
    { name: 'Jean-Christophe 3' },
    { name: 'Hakima 3' },
    { name: 'Aya 3' },
    { name: 'Virgil 3' },
    { name: 'Stéphane 3' },
    { name: 'Wendy 3' },
    { name: 'Oum 3' },
    { name: 'Jeremy 3' },
    { name: 'Claudia 3' },
    { name: 'Vincent 4' },
    { name: 'Kevin 4' },
    { name: 'Jean 4' },
    { name: 'Jean-Christophe 4' },
    { name: 'Hakima 4' },
    { name: 'Aya 4' },
    { name: 'Virgil 4' },
    { name: 'Stéphane 4' },
    { name: 'Wendy 4' },
    { name: 'Oum 4' },
    { name: 'Jeremy 4' },
    { name: 'Claudia 4' },
    { name: 'Vincent 5' },
    { name: 'Kevin 5' },
    { name: 'Jean 5' },
    { name: 'Jean-Christophe 5' },
    { name: 'Hakima 5' },
    { name: 'Aya 5' },
    { name: 'Virgil 5' },
    { name: 'Stéphane 5' },
    { name: 'Wendy 5' },
    { name: 'Oum 5' },
    { name: 'Jeremy 5' },
    { name: 'Claudia 5' },
];